# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thuvien.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItemModel, QStandardItem
from PyQt5.QtWidgets import QTableWidgetItem, QMessageBox, QWidget
import pymysql
import datetime
from PyQt5 import QtCore, QtGui, QtWidgets
from xlsxwriter import Workbook


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1195, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(90, 0, 1121, 601))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.today_tab = QtWidgets.QWidget()
        self.today_tab.setObjectName("today_tab")
        self.tableWidget = QtWidgets.QTableWidget(self.today_tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 1051, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.btnThem = QtWidgets.QPushButton(self.today_tab)
        self.btnThem.setGeometry(QtCore.QRect(950, 20, 91, 31))
        self.btnThem.setObjectName("btnThem")
        self.comboBox_mt = QtWidgets.QComboBox(self.today_tab)
        self.comboBox_mt.setGeometry(QtCore.QRect(530, 20, 81, 31))
        self.comboBox_mt.setObjectName("comboBox_mt")
        self.comboBox_mt.addItem("")
        self.comboBox_mt.addItem("")
        self.comboBox_day = QtWidgets.QComboBox(self.today_tab)
        self.comboBox_day.setGeometry(QtCore.QRect(700, 20, 71, 31))
        self.comboBox_day.setObjectName("comboBox_day")
        self.comboBox_day.addItem("")
        self.comboBox_day.addItem("")
        self.comboBox_day.addItem("")
        self.comboBox_day.addItem("")
        self.comboBox_day.addItem("")
        self.comboBox_day.addItem("")
        self.comboBox_day.addItem("")
        self.comboBox_day.addItem("")
        self.comboBox_day.addItem("")
        self.comboBox_day.addItem("")
        self.comboBox_day.addItem("")
        self.label_2 = QtWidgets.QLabel(self.today_tab)
        self.label_2.setGeometry(QtCore.QRect(650, 10, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtkhach = QtWidgets.QLineEdit(self.today_tab)
        self.txtkhach.setGeometry(QtCore.QRect(300, 20, 171, 31))
        self.txtkhach.setObjectName("txtkhach")
        self.btnXuat = QtWidgets.QPushButton(self.today_tab)
        self.btnXuat.setGeometry(QtCore.QRect(840, 480, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.btnXuat.setFont(font)
        self.btnXuat.setObjectName("btnXuat")
        self.txtkhach_2 = QtWidgets.QLineEdit(self.today_tab)
        self.txtkhach_2.setGeometry(QtCore.QRect(60, 20, 171, 31))
        self.txtkhach_2.setObjectName("txtkhach_2")
        self.tabWidget.addTab(self.today_tab, "")
        self.sach_tab = QtWidgets.QWidget()
        self.sach_tab.setObjectName("sach_tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.sach_tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 20, 1121, 471))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_10)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 0, 1111, 491))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(8)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, item)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEditnsach = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditnsach.setGeometry(QtCore.QRect(290, 30, 261, 31))
        self.lineEditnsach.setObjectName("lineEditnsach")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(190, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnSave = QtWidgets.QPushButton(self.tab_3)
        self.btnSave.setGeometry(QtCore.QRect(532, 360, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.formWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.formWidget_2.setGeometry(QtCore.QRect(610, 80, 411, 201))
        self.formWidget_2.setObjectName("formWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_20 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.formWidget_2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.comboBox_12 = QtWidgets.QComboBox(self.formWidget_2)
        self.comboBox_12.setObjectName("comboBox_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_12)
        self.label_21 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.comboBox_13 = QtWidgets.QComboBox(self.formWidget_2)
        self.comboBox_13.setObjectName("comboBox_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_13)
        self.label_22 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.comboBox_14 = QtWidgets.QComboBox(self.formWidget_2)
        self.comboBox_14.setObjectName("comboBox_14")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_14)
        self.label_23 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.formWidget_2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.label_24 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_31 = QtWidgets.QLabel(self.formWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.formWidget_2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_16)
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(30, 80, 491, 251))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_8.setGeometry(QtCore.QRect(640, 360, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 10, 261, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 50, 261, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_9.setGeometry(QtCore.QRect(572, 10, 171, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_25 = QtWidgets.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(160, 50, 82, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_10.setGeometry(QtCore.QRect(300, 360, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_2.setGeometry(QtCore.QRect(30, 90, 491, 251))
        self.textEdit_2.setObjectName("textEdit_2")
        self.formWidget_3 = QtWidgets.QWidget(self.tab_6)
        self.formWidget_3.setGeometry(QtCore.QRect(630, 100, 411, 221))
        self.formWidget_3.setObjectName("formWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formWidget_3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_26 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.formWidget_3)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_14)
        self.comboBox_15 = QtWidgets.QComboBox(self.formWidget_3)
        self.comboBox_15.setObjectName("comboBox_15")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_15)
        self.label_27 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.comboBox_16 = QtWidgets.QComboBox(self.formWidget_3)
        self.comboBox_16.setObjectName("comboBox_16")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_16)
        self.label_28 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.comboBox_17 = QtWidgets.QComboBox(self.formWidget_3)
        self.comboBox_17.setObjectName("comboBox_17")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_17)
        self.label_29 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.formWidget_3)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_15)
        self.label_30 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_38 = QtWidgets.QLabel(self.formWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.formWidget_3)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_17)
        self.label_5 = QtWidgets.QLabel(self.tab_6)
        self.label_5.setGeometry(QtCore.QRect(170, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_6)
        self.label_6.setGeometry(QtCore.QRect(170, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.pushButton_29 = QtWidgets.QPushButton(self.sach_tab)
        self.pushButton_29.setGeometry(QtCore.QRect(870, 490, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName("pushButton_29")
        self.tabWidget.addTab(self.sach_tab, "")
        self.khachhang_tab = QtWidgets.QWidget()
        self.khachhang_tab.setObjectName("khachhang_tab")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.khachhang_tab)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 20, 1121, 541))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_12)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 0, 1071, 431))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(3)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_28.setGeometry(QtCore.QRect(860, 440, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_22.setGeometry(QtCore.QRect(482, 320, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_25.setGeometry(QtCore.QRect(420, 220, 261, 31))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_24.setGeometry(QtCore.QRect(420, 150, 261, 31))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_35 = QtWidgets.QLabel(self.tab_13)
        self.label_35.setGeometry(QtCore.QRect(270, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_17 = QtWidgets.QLabel(self.tab_13)
        self.label_17.setGeometry(QtCore.QRect(270, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_34 = QtWidgets.QLabel(self.tab_13)
        self.label_34.setGeometry(QtCore.QRect(270, 220, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_9.setGeometry(QtCore.QRect(420, 90, 261, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.tabWidget_4.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.label_18 = QtWidgets.QLabel(self.tab_14)
        self.label_18.setGeometry(QtCore.QRect(170, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_23.setGeometry(QtCore.QRect(640, 360, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_10.setGeometry(QtCore.QRect(320, 10, 261, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_24.setGeometry(QtCore.QRect(650, 10, 171, 31))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_25.setGeometry(QtCore.QRect(300, 360, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_27.setGeometry(QtCore.QRect(370, 170, 261, 31))
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_26.setGeometry(QtCore.QRect(370, 110, 261, 31))
        self.lineEdit_26.setText("")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_37 = QtWidgets.QLabel(self.tab_14)
        self.label_37.setGeometry(QtCore.QRect(220, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_36 = QtWidgets.QLabel(self.tab_14)
        self.label_36.setGeometry(QtCore.QRect(220, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_28.setGeometry(QtCore.QRect(370, 240, 261, 31))
        self.lineEdit_28.setText("")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_19 = QtWidgets.QLabel(self.tab_14)
        self.label_19.setGeometry(QtCore.QRect(220, 170, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.tabWidget_4.addTab(self.tab_14, "")
        self.tabWidget.addTab(self.khachhang_tab, "")
        self.edit_tab = QtWidgets.QWidget()
        self.edit_tab.setObjectName("edit_tab")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.edit_tab)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 20, 1051, 451))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 111, 1051, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_14.setGeometry(QtCore.QRect(792, 30, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_4 = QtWidgets.QLabel(self.tab_7)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_5.setGeometry(QtCore.QRect(222, 30, 191, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_15.setGeometry(QtCore.QRect(800, 30, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_32 = QtWidgets.QLabel(self.tab_9)
        self.label_32.setGeometry(QtCore.QRect(68, 30, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_6.setGeometry(QtCore.QRect(220, 30, 191, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_3.setGeometry(QtCore.QRect(-2, 111, 1051, 291))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_16.setGeometry(QtCore.QRect(800, 29, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_33 = QtWidgets.QLabel(self.tab_8)
        self.label_33.setGeometry(QtCore.QRect(38, 29, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_13.setGeometry(QtCore.QRect(220, 29, 191, 41))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_4.setGeometry(QtCore.QRect(-2, 110, 1051, 291))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tabWidget.addTab(self.edit_tab, "")
        self.thongke_tab = QtWidgets.QWidget()
        self.thongke_tab.setObjectName("thongke_tab")
        self.listView = QtWidgets.QListView(self.thongke_tab)
        self.listView.setGeometry(QtCore.QRect(40, 80, 1021, 391))
        self.listView.setObjectName("listView")
        self.thongkebtn = QtWidgets.QPushButton(self.thongke_tab)
        self.thongkebtn.setGeometry(QtCore.QRect(40, 17, 111, 41))
        self.thongkebtn.setObjectName("thongkebtn")
        self.tabWidget.addTab(self.thongke_tab, "")
        self.pushButton_today = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_today.setGeometry(QtCore.QRect(10, 60, 71, 61))
        self.pushButton_today.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/today.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_today.setIcon(icon)
        self.pushButton_today.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_today.setObjectName("pushButton_today")
        self.pushButton_tacgia = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tacgia.setGeometry(QtCore.QRect(10, 470, 71, 71))
        self.pushButton_tacgia.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/auth.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_tacgia.setIcon(icon1)
        self.pushButton_tacgia.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_tacgia.setObjectName("pushButton_tacgia")
        self.pushButton_sach = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sach.setGeometry(QtCore.QRect(10, 180, 71, 61))
        self.pushButton_sach.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_sach.setIcon(icon2)
        self.pushButton_sach.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_sach.setObjectName("pushButton_sach")
        self.pushButton_user = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_user.setGeometry(QtCore.QRect(10, 330, 71, 61))
        self.pushButton_user.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_user.setIcon(icon3)
        self.pushButton_user.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_user.setObjectName("pushButton_user")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1195, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quản lý thư viện "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tên sách"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Khách hàng"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Trạng thái"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Số ngày"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Ngày mượn"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Ngày trả"))
        self.btnThem.setText(_translate("MainWindow", "Thêm"))
        self.comboBox_mt.setItemText(0, _translate("MainWindow", "Mượn"))
        self.comboBox_mt.setItemText(1, _translate("MainWindow", "Trả"))
        self.comboBox_day.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_day.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_day.setItemText(2, _translate("MainWindow", "2"))
        self.comboBox_day.setItemText(3, _translate("MainWindow", "3"))
        self.comboBox_day.setItemText(4, _translate("MainWindow", "4"))
        self.comboBox_day.setItemText(5, _translate("MainWindow", "5"))
        self.comboBox_day.setItemText(6, _translate("MainWindow", "6"))
        self.comboBox_day.setItemText(7, _translate("MainWindow", "7"))
        self.comboBox_day.setItemText(8, _translate("MainWindow", "8"))
        self.comboBox_day.setItemText(9, _translate("MainWindow", "9"))
        self.comboBox_day.setItemText(10, _translate("MainWindow", "10"))
        self.label_2.setText(_translate("MainWindow", "Ngày"))
        self.txtkhach.setPlaceholderText(_translate("MainWindow", "Nhập ID khách"))
        self.btnXuat.setText(_translate("MainWindow", "Export Operations  to CSV"))
        self.txtkhach_2.setPlaceholderText(_translate("MainWindow", "Nhập ID sách"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.today_tab), _translate("MainWindow", "Mượn/Trả"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tên sách"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mô tả"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mã sách"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Thẻ loại"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gía tiền"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tác giả"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Nhà xuất bản"))
        item = self.tableWidget_5.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Số lượng"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "Danh sách"))
        self.label_3.setText(_translate("MainWindow", "Tên sách"))
        self.btnSave.setText(_translate("MainWindow", "Lưu"))
        self.label_20.setText(_translate("MainWindow", "Mã sách"))
        self.label_21.setText(_translate("MainWindow", "Thẻ loại"))
        self.label_22.setText(_translate("MainWindow", "Tác giả"))
        self.label_23.setText(_translate("MainWindow", "Nhà xuất bản"))
        self.label_24.setText(_translate("MainWindow", "Gía tiền"))
        self.label_31.setText(_translate("MainWindow", "Số lượng"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Thêm sách"))
        self.pushButton_8.setText(_translate("MainWindow", "Lưu"))
        self.pushButton_9.setText(_translate("MainWindow", "Search"))
        self.pushButton_10.setText(_translate("MainWindow", "Xoá"))
        self.label_26.setText(_translate("MainWindow", "Mã sách"))
        self.label_27.setText(_translate("MainWindow", "Thẻ loại"))
        self.label_28.setText(_translate("MainWindow", "Tác giả"))
        self.label_29.setText(_translate("MainWindow", "Nhà xuất bản"))
        self.label_30.setText(_translate("MainWindow", "Gía tiền"))
        self.label_38.setText(_translate("MainWindow", "Số lượng"))
        self.label_5.setText(_translate("MainWindow", "Tên sách"))
        self.label_6.setText(_translate("MainWindow", "Tên sách"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Sửa hoặc xoá sách"))
        self.pushButton_29.setText(_translate("MainWindow", "Export Books Data to CSV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sach_tab), _translate("MainWindow", "SÁCH"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên khách hàng"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SDT/Email"))
        self.pushButton_28.setText(_translate("MainWindow", "Export Client Data to CSV"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("MainWindow", "Danh sách"))
        self.pushButton_22.setText(_translate("MainWindow", "Thêm "))
        self.label_35.setText(_translate("MainWindow", "SDT/Email"))
        self.label_17.setText(_translate("MainWindow", "Tên khách hàng"))
        self.label_34.setText(_translate("MainWindow", "ID"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("MainWindow", "Thêm khách hàng"))
        self.label_18.setText(_translate("MainWindow", "ID Khách hàng"))
        self.pushButton_23.setText(_translate("MainWindow", "Lưu"))
        self.pushButton_24.setText(_translate("MainWindow", "Search"))
        self.pushButton_25.setText(_translate("MainWindow", "Xoá"))
        self.label_37.setText(_translate("MainWindow", "SDT/Email"))
        self.label_36.setText(_translate("MainWindow", "ID"))
        self.label_19.setText(_translate("MainWindow", "Tên khách hàng"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14),
                                    _translate("MainWindow", "Sửa hoặc xoá sách"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.khachhang_tab), _translate("MainWindow", "KHÁCH HÀNG"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Thể loại"))
        self.pushButton_14.setText(_translate("MainWindow", "Thêm thể loại"))
        self.label_4.setText(_translate("MainWindow", "Thể loại mới"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Thêm thể loại"))
        self.pushButton_15.setText(_translate("MainWindow", "Thêm tác giả"))
        self.label_32.setText(_translate("MainWindow", "Tác giả mới"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tác giả"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Thêm tác giả"))
        self.pushButton_16.setText(_translate("MainWindow", "Thêm nhà xuất bản"))
        self.label_33.setText(_translate("MainWindow", "Nhà xuất bản mới"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nhà xuất bản"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Thêm nhà xuất bản"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.edit_tab), _translate("MainWindow", "EDIT"))
        self.thongkebtn.setText(_translate("MainWindow", "Thống kê"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.thongke_tab), _translate("MainWindow", "Thống kê"))

    def xulybtn(self):
        self.pushButton_today.clicked.connect(lambda: self.tabWidget.setCurrentIndex(0))
        self.pushButton_sach.clicked.connect(lambda: self.tabWidget.setCurrentIndex(1))
        self.pushButton_user.clicked.connect(lambda: self.tabWidget.setCurrentIndex(2))
        self.pushButton_tacgia.clicked.connect(lambda: self.tabWidget.setCurrentIndex(3))
        # tab sách
        self.btnSave.clicked.connect(self.them_sach)
        self.pushButton_10.clicked.connect(self.xoa_sach)
        self.pushButton_9.clicked.connect(self.tim_sach)
        self.pushButton_8.clicked.connect(self.sua_sach)
        # edit tab
        self.pushButton_14.clicked.connect(self.them_the_loai)
        self.pushButton_15.clicked.connect(self.them_tac_gia)
        self.pushButton_16.clicked.connect(self.them_nhaxb)
        # khach hang tab
        self.pushButton_22.clicked.connect(self.them_khach_hang)
        self.pushButton_24.clicked.connect(self.tim_khach_hang)
        self.pushButton_25.clicked.connect(self.xoa_khach_hang)
        self.pushButton_23.clicked.connect(self.sua_khach_hang)
        # tab muontra
        self.btnThem.clicked.connect(self.muontra)
        #xuat
        self.btnXuat.clicked.connect(self.Export_muontra)
        self.pushButton_29.clicked.connect(self.Export_sach)
        self.pushButton_28.clicked.connect(self.Export_khach)
        #thống kê
        self.thongkebtn.clicked.connect(self.thong_ke)

    def Export_muontra(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute('''
            SELECT masach, makhach, trangthai, ngay, ngaymuon, ngaytra FROM muontra
        ''')
        data = self.cur.fetchall()


        wbook = Workbook('Mượn_Trả.xlsx')
        sheet1 = wbook.add_worksheet()

        sheet1.write(0,0, 'Tên sách')
        sheet1.write(0,1, 'Tên khách')
        sheet1.write(0,2, 'Trạng thái')
        sheet1.write(0,3, 'Số ngày')
        sheet1.write(0,4, 'Ngày mượn')
        sheet1.write(0,5,'Ngày trả')

        row_num = 1
        for row in data:
            colum_number =0
            for item in row:
                sheet1.write(row_num, colum_number, str(item))
                colum_number +=1
            row_num += 1
        wbook.close()
        tb = QMessageBox()
        tb.setWindowTitle("Thông báo")
        tb.setText("Tạo báo cáo thành công")
        tb.exec_()

    def Export_khach(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT makhach, tenkhach, SDT_email  FROM khachhang''')
        data = self.cur.fetchall()

        wbook = Workbook('Khach hang.xlsx')
        sheet1 = wbook.add_worksheet()

        sheet1.write(0,0, 'Mã khách')
        sheet1.write(0,1, 'Tên khách')
        sheet1.write(0,2, 'SDT_email')

        row_num = 1
        for row in data:
            colum_number =0
            for item in row:
                sheet1.write(row_num, colum_number, str(item))
                colum_number +=1
            row_num += 1
        wbook.close()
        tb = QMessageBox()
        tb.setWindowTitle("Thông báo")
        tb.setText("Tạo báo cáo thành công")
        tb.exec_()

    def Export_sach(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT  tensach, mota, masach, theloai, giatien, tacgia, nhaxuatban, soluong  FROM book''')
        data = self.cur.fetchall()

        wbook = Workbook('sach.xlsx')
        sheet1 = wbook.add_worksheet()

        sheet1.write(0,0, 'Tên sách')
        sheet1.write(0,1, 'Mô tả')
        sheet1.write(0,2, 'Mã sách')
        sheet1.write(0,3, 'Thể loại')
        sheet1.write(0,4, 'Gía tiền')
        sheet1.write(0,5, 'Tác giả')
        sheet1.write(0,6, 'Nhà xuat bản')
        sheet1.write(0, 7, 'Số lượng')


        row_num = 1
        for row in data:
            colum_number =0
            for item in row:
                sheet1.write(row_num, colum_number, str(item))
                colum_number +=1
            row_num += 1
        wbook.close()
        tb = QMessageBox()
        tb.setWindowTitle("Thông báo")
        tb.setText("Tạo báo cáo thành công")
        tb.exec_()
    #########################################
    # CODE TAB_MUON/TRA
    #########################################
    def muontra(self):
        global cur, db
        tensach = self.txtkhach_2.text()
        tenkhach = self.txtkhach.text()
        trangthai = self.comboBox_mt.currentText()
        songay = self.comboBox_day.currentIndex()
        ngaymuon = datetime.date.today()
        ngaytra = ngaymuon + datetime.timedelta(days=int(songay))

        try:
            db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
            cur = db.cursor()

            if trangthai == "Mượn":
                cur.execute(''' SELECT soluong FROM book WHERE masach = %s ''', (tensach,))
                demsach = cur.fetchone()[0]

                if demsach <= 0:
                    tb = QMessageBox()
                    tb.setWindowTitle("Thông báo")
                    tb.setText("Hết sách!")
                    tb.exec_()
                    return

                cur.execute(''' INSERT INTO muontra (masach, makhach, trangthai, ngay, ngaymuon, ngaytra)
                                VALUES (%s, %s, %s, %s, %s, %s) 
                            ''', (tensach, tenkhach, trangthai, songay, ngaymuon, ngaytra))

                new_quantity = demsach - 1
                cur.execute(''' UPDATE book SET soluong = %s WHERE masach = %s ''', (new_quantity, tensach))

            elif trangthai == "Trả":
                cur.execute(''' SELECT COUNT(*) FROM muontra WHERE makhach = %s AND trangthai = 'Mượn' ''', (tenkhach,))
                current_borrowed_count = cur.fetchone()[0]

                if current_borrowed_count <= 0:
                    tb = QMessageBox()
                    tb.setWindowTitle("Thông báo")
                    tb.setText("Bạn không có sách để trả!")
                    tb.exec_()
                    return

                cur.execute(''' INSERT INTO muontra (masach, makhach, trangthai, ngaytra)
                                VALUES (%s, %s, %s, %s) 
                            ''', (tensach, tenkhach, trangthai, ngaytra))

                cur.execute(''' SELECT soluong FROM book WHERE masach = %s ''', (tensach,))
                demsach = cur.fetchone()[0]

                new_quantity = demsach + 1
                cur.execute(''' UPDATE book SET soluong = %s WHERE masach = %s ''', (new_quantity, tensach))

            db.commit()
            self.hien_sach()
            tb = QMessageBox()
            tb.setWindowTitle("Thông báo")
            tb.setText("Thao tác thành công")
            tb.exec_()
            self.hien_muontra()

        except pymysql.Error as e:
            print(f"Error: {e}")
            if db:
                db.rollback()


    def hien_muontra(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute('''
                       SELECT book.tensach, khachhang.tenkhach, muontra.trangthai,muontra.ngay, muontra.ngaymuon, muontra.ngaytra
                       FROM muontra
                       INNER JOIN book ON muontra.masach = book.masach
                       INNER JOIN khachhang ON muontra.makhach = khachhang.makhach
                   ''')
        data = self.cur.fetchall()

        self.tableWidget.setRowCount(0)

        for row, form in enumerate(data):
            self.tableWidget.insertRow(row)
            for col, item in enumerate(form):
                if col == 3 and form[2] == 'Mượn':
                    ngay_muon = item.strftime('%Y-%m-%d') if isinstance(item, datetime.datetime) else str(item)
                    self.tableWidget.setItem(row, col, QTableWidgetItem(ngay_muon))
                elif col == 4 and form[2] == 'Mượn':  # Assuming ngaytra (return date) is at index 4
                    ngay_tra = item.strftime('%Y-%m-%d') if isinstance(item, datetime.datetime) else str(item)
                    self.tableWidget.setItem(row, col, QTableWidgetItem(ngay_tra))
                else:
                    self.tableWidget.setItem(row, col, QTableWidgetItem(str(item)))

        self.db.close()

    #########################################
    # CODE TAB_SÁCH
    #########################################
    def them_sach(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        tensach = self.lineEditnsach.text()
        mota = self.textEdit.toPlainText()
        masach = self.lineEdit_11.text()
        theloai = self.comboBox_12.currentText()
        tacgia = self.comboBox_13.currentText()
        nhaxuatban = self.comboBox_14.currentText()
        gia = self.lineEdit_12.text()
        soluong = self.lineEdit_16.text()

        self.cur.execute('''
           INSERT INTO book ( tensach, mota, masach, theloai, giatien, tacgia, nhaxuatban, soluong)
           VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
           ''', (tensach, mota, masach, theloai, tacgia, nhaxuatban, gia, soluong,))

        self.db.commit()
        tb = QMessageBox()
        tb.setWindowTitle("Thông báo")
        tb.setText("Thêm thành công")
        tb.exec_()

        self.lineEditnsach.setText('')
        self.textEdit.setPlainText('')
        self.lineEdit_11.setText('')
        self.comboBox_12.setCurrentText(str(0))
        self.comboBox_13.setCurrentText(str(0))
        self.comboBox_14.setCurrentText(str(0))
        self.lineEdit_12.setText('')
        self.hien_sach()

    def sua_sach(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        tensach = self.lineEdit_4.text()
        mota = self.textEdit_2.toPlainText()
        masach = self.lineEdit_14.text()
        theloai = self.comboBox_15.currentText()
        tacgia = self.comboBox_16.currentText()
        nhaxuatban = self.comboBox_17.currentText()
        gia = self.lineEdit_15.text()
        soluong = self.lineEdit_17.text()

        search_term = self.lineEdit_3.text()

        self.cur.execute('''
           UPDATE book SET tensach=%s, mota=%s, masach=%s, theloai=%s, giatien=%s, tacgia=%s, nhaxuatban=%s, soluong=%s
           WHERE tensach =%s ''',
                         (tensach, mota, masach, theloai, gia, tacgia, nhaxuatban,soluong, search_term))

        self.db.commit()
        tb = QMessageBox()
        tb.setWindowTitle("Thông báo")
        tb.setText("Sửa thành công")
        tb.exec_()
        self.hien_sach()

    def xoa_sach(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        todelete = self.lineEdit_3.text()
        warning = QMessageBox.warning(None, 'Xoá sách', 'Bạn chắc chắn muốn xoá sách ?',
                                      QMessageBox.Yes | QMessageBox.No)

        if warning == QMessageBox.Yes:
            SQL = '''DELETE FROM book WHERE tensach=%s'''
            self.cur.execute(SQL, [todelete])
            self.db.commit()
            tb = QMessageBox()
            tb.setWindowTitle("Thông báo")
            tb.setText("Xoá thành công")
            tb.exec_()
            self.hien_sach()
            pass

    def hien_sach(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT  tensach, mota, masach, theloai, giatien, tacgia, nhaxuatban, soluong  FROM book''')
        data = self.cur.fetchall()

        self.tableWidget_5.setRowCount(0)
        self.tableWidget_5.insertRow(0)

        for row, form in enumerate(data):
            for colum, item in enumerate(form):
                self.tableWidget_5.setItem(row, colum, QTableWidgetItem(str(item)))
                colum += 1

            row_position = self.tableWidget_5.rowCount()
            self.tableWidget_5.insertRow(row_position)

        self.db.close()

    def tim_sach(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        book_title = self.lineEdit_3.text()

        SQL = ''' SELECT * FROM book WHERE tensach = %s'''
        self.cur.execute(SQL, [book_title])

        data = self.cur.fetchone()

        if data:
            self.lineEdit_4.setText(data[0])
            self.textEdit_2.setPlainText(data[1])
            self.lineEdit_14.setText(data[2])
            self.comboBox_15.setCurrentText(str(data[3]))
            self.comboBox_16.setCurrentText(str(data[4]))
            self.comboBox_17.setCurrentText(str(data[5]))
            self.lineEdit_15.setText(str(data[6]))
            self.lineEdit_17.setText(str(data[7]))
        else:

            self.lineEdit_4.setText('')
            self.textEdit_2.setPlainText('')
            self.lineEdit_14.setText('')
            self.comboBox_15.setCurrentText('')
            self.comboBox_16.setCurrentText('')
            self.comboBox_17.setCurrentText('')
            self.lineEdit_15.setText('')
            self.lineEdit_17.setText('')

            print("Không tìm thấy sách.")

    #########################################
    # Code tab Khách hàng
    #########################################

    def them_khach_hang(self):
        tenkhachhang = self.lineEdit_9.text()
        email = self.lineEdit_24.text()
        id = self.lineEdit_25.text()

        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute('''
              INSERT INTO khachhang(makhach, tenkhach, SDT_email)
              VALUES (%s, %s, %s)
              ''', (id, tenkhachhang, email,))
        self.db.commit()
        self.db.close()
        tb = QMessageBox()
        tb.setWindowTitle("Thông báo")
        tb.setText("Thêm thành công")
        tb.exec_()
        self.hien_khach_hang()

    def hien_khach_hang(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT makhach, tenkhach, SDT_email  FROM khachhang''')
        data = self.cur.fetchall()

        self.tableWidget_6.setRowCount(0)
        self.tableWidget_6.insertRow(0)

        for row, form in enumerate(data):
            for colum, item in enumerate(form):
                self.tableWidget_6.setItem(row, colum, QTableWidgetItem(str(item)))
                colum += 1

            row_position = self.tableWidget_6.rowCount()
            self.tableWidget_6.insertRow(row_position)

        self.db.close()

    def sua_khach_hang(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        id = self.lineEdit_10.text()
        idmoi = self.lineEdit_26.text()
        tenkhachhang = self.lineEdit_27.text()
        email = self.lineEdit_28.text()

        self.cur.execute('''
                  UPDATE khachhang SET makhach=%s, tenkhach=%s, SDT_email=%s WHERE makhach=%s
              ''', (idmoi, tenkhachhang, email, id))

        self.db.commit()
        self.db.close()
        tb = QMessageBox()
        tb.setWindowTitle("Thông báo")
        tb.setText("Sửa thành công")
        tb.exec_()
        self.hien_khach_hang()

    def xoa_khach_hang(self):
        delete_new_id = self.lineEdit_10.text()

        Warning_message = QMessageBox.warning(None, 'Xoá sách', 'Bạn chắc chắn muốn xoá sách ?',
                                              QMessageBox.Yes | QMessageBox.No)

        if Warning_message == QMessageBox.Yes:
            self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
            self.cur = self.db.cursor()

            SQL = '''
                      DELETE FROM khachhang WHERE makhach = %s
                  '''
            self.cur.execute(SQL, [delete_new_id])
            self.db.commit()
            self.db.close()
            tb = QMessageBox()
            tb.setWindowTitle("Thông báo")
            tb.setText("Xoá thành công")
            tb.exec_()
            self.hien_khach_hang()

    def tim_khach_hang(self):
        client_national = self.lineEdit_10.text()
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        sql = '''SELECT * FROM khachhang WHERE makhach = %s '''

        self.cur.execute(sql, [client_national])
        data = self.cur.fetchone()

        self.lineEdit_26.setText(data[0])
        self.lineEdit_27.setText(data[1])
        self.lineEdit_28.setText(data[2])

    #########################################

    def them_the_loai(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        tentheloai = self.lineEdit_5.text()

        self.cur.execute('''
           INSERT INTO theloai(theloai) VALUES (%s)
           ''', (tentheloai,))
        self.db.commit()
        self.lineEdit_5.setText('')
        tb = QMessageBox()
        tb.setWindowTitle("Thông báo")
        tb.setText("Thêm thành công")
        tb.exec_()
        self.hien_the_loai()
        self.hien_theloai_combobox()

    def hien_the_loai(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT theloai FROM theloai ''')
        category_data = self.cur.fetchall()

        if category_data:
            self.tableWidget_2.setRowCount(0)
            self.tableWidget_2.insertRow(0)
            for row, form in enumerate(category_data):
                for column, item in enumerate(form):
                    self.tableWidget_2.setItem(row, column, QTableWidgetItem(str(item)))
                    column += 1

                row_postion = self.tableWidget_2.rowCount()
                self.tableWidget_2.insertRow(row_postion)

    def them_tac_gia(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        tacgia = self.lineEdit_6.text()

        self.cur.execute('''
                  INSERT INTO tacgia(tentacgia) VALUES (%s)
                  ''', (tacgia,))
        self.db.commit()
        self.lineEdit_6.setText('')
        tb = QMessageBox()
        tb.setWindowTitle("Thông báo")
        tb.setText("Thêm thành công")
        tb.exec_()
        self.hien_tac_gia()
        self.hien_tacgia_combobox()

    def hien_tac_gia(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT tentacgia FROM tacgia ''')
        data = self.cur.fetchall()

        if data:
            self.tableWidget_3.setRowCount(0)
            self.tableWidget_3.insertRow(0)
            for row, form in enumerate(data):
                for column, item in enumerate(form):
                    self.tableWidget_3.setItem(row, column, QTableWidgetItem(str(item)))
                    column += 1

                row_postion = self.tableWidget_3.rowCount()
                self.tableWidget_3.insertRow(row_postion)

    def them_nhaxb(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        nhaxb = self.lineEdit_13.text()

        self.cur.execute('''
                          INSERT INTO nhaxuatban(nhaxb) VALUES (%s)
                          ''', (nhaxb,))
        self.db.commit()
        self.lineEdit_13.setText('')
        tb = QMessageBox()
        tb.setWindowTitle("Thông báo")
        tb.setText("Thêm thành công")
        tb.exec_()
        self.hien_nhaxb()
        self.hien_nhaxb_combobox()

    def hien_nhaxb(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT nhaxb FROM nhaxuatban ''')
        publisher_data = self.cur.fetchall()

        if publisher_data:
            self.tableWidget_4.setRowCount(0)
            self.tableWidget_4.insertRow(0)
            for row, form in enumerate(publisher_data):
                for column, item in enumerate(form):
                    self.tableWidget_4.setItem(row, column, QTableWidgetItem(str(item)))
                    column += 1

                row_postion = self.tableWidget_4.rowCount()
                self.tableWidget_4.insertRow(row_postion)

    def hien_theloai_combobox(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT theloai FROM theloai ''')
        combodata = self.cur.fetchall()

        self.comboBox_12.clear()
        for category in combodata:
            self.comboBox_12.addItem(category[0])
            self.comboBox_15.addItem(category[0])

    def hien_tacgia_combobox(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT tentacgia FROM tacgia ''')
        combodata = self.cur.fetchall()

        self.comboBox_13.clear()
        for author in combodata:
            self.comboBox_13.addItem(author[0])
            self.comboBox_16.addItem(author[0])

    def hien_nhaxb_combobox(self):
        self.db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
        self.cur = self.db.cursor()

        self.cur.execute(''' SELECT nhaxb FROM nhaxuatban ''')
        combodata = self.cur.fetchall()

        self.comboBox_14.clear()
        for publisher in combodata:
            self.comboBox_14.addItem(publisher[0])
            self.comboBox_17.addItem(publisher[0])

    def thong_ke(self):
        try:
            db = pymysql.connect(host='localhost', user='root', password='', db='qlthuvien')
            cur = db.cursor()

            cur.execute(''' SELECT COUNT(*) FROM muontra WHERE trangthai = 'Mượn' ''')
            sach_muon = cur.fetchone()[0]

            cur.execute(''' SELECT COUNT(*) FROM muontra WHERE trangthai = 'Trả' ''')
            sach_tra = cur.fetchone()[0]

            cur.execute(''' SELECT SUM(soluong) FROM book ''')
            tong_sach = cur.fetchone()[0]

            cur.execute(''' SELECT COUNT(*) FROM muontra WHERE trangthai = 'Mượn' AND DATE(ngaymuon) = CURDATE() ''')
            sach_muon_hom_nay = cur.fetchone()[0]

            cur.execute('''
                        SELECT masach, COUNT(*) AS so_luong
                        FROM muontra
                        WHERE trangthai = 'Mượn'
                        GROUP BY masach
                        ORDER BY so_luong DESC
                        LIMIT 5
                    ''')
            sach_muon_nhieu_nhat = cur.fetchall()

            cur.execute('''
                        SELECT masach, soluong
                        FROM book
                        ORDER BY soluong ASC
                        LIMIT 5
                    ''')
            sach_it_nhat = cur.fetchall()

            cur.close()
            db.close()


            results = [
                f"Số lượng sách đã mượn: {sach_muon}",
                f"Số lượng sách đã trả: {sach_tra}",
                f"Tổng số lượng sách: {tong_sach}",
                f"Số lượng sách đã mượn hôm nay: {sach_muon_hom_nay}",
                "Sách được mượn nhiều nhất:",
            ]

            for book in sach_muon_nhieu_nhat:
                results.append(f"  - Mã sách: {book[0]}, Số lần mượn: {book[1]}")

            results.append("Sách có sẵn ít nhất:")

            for book in sach_it_nhat:
                results.append(f"  - Mã sách: {book[0]}, Số lượng: {book[1]}")

            model = QStandardItemModel()
            for result in results:
                item = QStandardItem(result)
                model.appendRow(item)

            self.listView.setModel(model)

        except pymysql.Error as e:
            print(f"Error: {e}")






import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.xulybtn()
    ui.hien_tac_gia()
    ui.hien_sach()
    ui.hien_nhaxb()
    ui.hien_the_loai()
    ui.hien_tacgia_combobox()
    ui.hien_nhaxb_combobox()
    ui.hien_theloai_combobox()
    ui.hien_khach_hang()
    ui.hien_muontra()
    ui.thong_ke()
    sys.exit(app.exec_())
